http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

db:
  databaseName: RoommateTap
  databaseHost: localhost
  databasePort: 5432
  databaseSslmode: disable
  databaseUser: postgres
  databasePassword: 1079

cache:
  ttl: 60s

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h #30 days
  verificationCodeLength: 8

limiter:
  rps: 10
  burst: 20
  ttl: 10m

email:
  templates:
    verification_email: "./templates/verification_email.html"
    purchase_successful: "./templates/purchase_successful.html"
  subjects:
    verification_email: "Спасибо за регистрацию, %s!"
    purchase_successful: "Покупка прошла успешно!"

smtp:
  host: smtp.gmail.com
  port: 587
  from: musabecova05@gmail.com
